!function(e){var n={};function r(_){if(n[_])return n[_].exports;var o=n[_]={i:_,l:!1,exports:{}};return e[_].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=n,r.d=function(e,n,_){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:_})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var _=Object.create(null);if(r.r(_),Object.defineProperty(_,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)r.d(_,o,function(n){return e[n]}.bind(null,o));return _},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/functions/header.js":
/*!************************************!*\
  !*** ./src/js/functions/header.js ***!
  \************************************/
/*! exports provided: headerBackgroundParallax */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"headerBackgroundParallax\", function() { return headerBackgroundParallax; });\n\n\nvar headerBackgroundParallax = function headerBackgroundParallax() {\n  var image = document.querySelector('.header');\n  window.addEventListener('scroll', function () {\n    var offset = window.pageYOffset;\n\n    if (window.matchMedia(\"(min-width: 1000px)\").matches) {\n      image.style.backgroundPositionY = offset * 0.7 + 'px';\n    }\n  });\n};\n\n//# sourceURL=webpack:///./src/js/functions/header.js?")},"./src/js/functions/overlay-menu.js":
/*!******************************************!*\
  !*** ./src/js/functions/overlay-menu.js ***!
  \******************************************/
/*! exports provided: overlayMenu */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"overlayMenu\", function() { return overlayMenu; });\n\n\nfunction overlayMenu() {\n  var burger = document.querySelector('.burger');\n  var overlayMenuSelector = document.querySelector('.overlay-menu');\n  burger.addEventListener('click', function () {\n    overlayMenuSelector.classList.toggle('overlay-menu--visible');\n  });\n}\n\n//# sourceURL=webpack:///./src/js/functions/overlay-menu.js?")},"./src/js/functions/preloader.js":
/*!***************************************!*\
  !*** ./src/js/functions/preloader.js ***!
  \***************************************/
/*! exports provided: preloader */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"preloader\", function() { return preloader; });\nvar preloader = function preloader() {\n  var preloaderSelector = document.querySelector('.preloader');\n\n  window.onload = function () {\n    preloaderSelector.style.transitionDuration = '0.5s';\n    preloaderSelector.classList.add('preloader--loaded');\n    setTimeout(function () {\n      return preloaderSelector.style.zIndex = '-1';\n    }, 500);\n  };\n};\n\n//# sourceURL=webpack:///./src/js/functions/preloader.js?")},"./src/js/functions/sticky-nav.js":
/*!****************************************!*\
  !*** ./src/js/functions/sticky-nav.js ***!
  \****************************************/
/*! exports provided: stickyNav */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"stickyNav\", function() { return stickyNav; });\n\n\nvar stickyNav = function stickyNav() {\n  var stickyNav = document.querySelector('.sticky-nav');\n\n  if (window.scrollY > 90) {\n    stickyNav.classList.add('sticky-nav--scroll');\n  }\n\n  function onScroll() {\n    window.addEventListener('scroll', callbackFunc);\n\n    function callbackFunc() {\n      var y = window.pageYOffset;\n\n      if (y > 90) {\n        stickyNav.classList.add('sticky-nav--scroll');\n        stickyNav.style.transition = '0.5s';\n      } else {\n        stickyNav.classList.remove('sticky-nav--scroll');\n        stickyNav.classList.remove('offset');\n      }\n    }\n  }\n\n  onScroll();\n};\n\n//# sourceURL=webpack:///./src/js/functions/sticky-nav.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _functions_preloader__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./functions/preloader */ "./src/js/functions/preloader.js");\n/* harmony import */ var _functions_overlay_menu__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./functions/overlay-menu */ "./src/js/functions/overlay-menu.js");\n/* harmony import */ var _functions_sticky_nav__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./functions/sticky-nav */ "./src/js/functions/sticky-nav.js");\n/* harmony import */ var _functions_header__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./functions/header */ "./src/js/functions/header.js");\n // import \'./vendor/focus-visible.min.js\';\n// import \'./_vars\';\n// import {resizeContent} from \'./functions/resize\';\n// import {scrollTo} from \'./functions/smooth-scroll\';\n// import {disableScroll, enableScroll} from \'./functions/stop-scroll\';\n\n\n\n\n\nObject(_functions_preloader__WEBPACK_IMPORTED_MODULE_0__["preloader"])();\nObject(_functions_overlay_menu__WEBPACK_IMPORTED_MODULE_1__["overlayMenu"])();\nObject(_functions_sticky_nav__WEBPACK_IMPORTED_MODULE_2__["stickyNav"])();\nObject(_functions_header__WEBPACK_IMPORTED_MODULE_3__["headerBackgroundParallax"])(); //disableScroll(fix) // fix -> class of element with position: fixed\n\n//# sourceURL=webpack:///./src/js/main.js?')}});